default:
    extensions:
        Behat\Symfony2Extension: ~
        Behat\MinkExtension:
            base_url: 'http://charla.dev:8080/app_test.php'
            browser_name: firefox
            sessions:
                default:
                    symfony2: ~
                javascript:
                    selenium2: ~
            show_cmd: open -a Google\ Chrome %s
    suites:
        test_suite:
            type: symfony_bundle
            bundle: 'AcmeDemoBundle'


