fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix: /secure_area

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /secure_area/connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /secure_area/connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /secure_area/connect

facebook_login:
    pattern: /secure_area/login_facebook

_security_check:
    pattern:  /login_check

_security_logout:
    pattern:  /logout
